version: "3.9"

services:
  backend:
    build: .
    container_name: football_backend
    restart: always
    env_file: .env
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    networks:
      - footnet

  postgres:
    image: postgres:14
    container_name: football_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: football
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - footnet

  pgadmin:
    image: dpage/pgadmin4
    container_name: football_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - footnet

networks:
  footnet:

volumes:
  pgdata:
